import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    fontFamily: 'Pretendard',
  },
  logincontainer: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 20,
    fontFamily: 'Pretendard',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    fontSize: 14,
    color: '#808080',
    fontFamily: 'Pretendard',
  },
  header: {
    padding: 15,
    paddingTop: 20,
    fontFamily: 'Pretendard',
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#5772FF',
    fontFamily: 'Pretendard',
  },
  subtitle: {
    fontSize: 26,
    whiteSpace: "nowrap",
    fontWeight: '700',
    marginLeft: 20,
    fontFamily: 'Pretendard',
  },
  description: {
    fontSize: 16,
    textAlign: 'left',
    color: '#898989',
    marginBottom: 10,
    marginTop: -10,
    marginLeft: 20,
    fontFamily: 'Pretendard',
    letterSpacing: -0.5, 
  },
  formGroup: {
    width: '100%',
    paddingHorizontal: 20,
    marginBottom: 20,
    fontFamily: 'Pretendard',
  },
  backText: {
    fontSize: 18,
    color: '#808080',
    fontFamily: 'Pretendard',
  },
  backButton: {
    position: 'absolute',
    top: 20,
    left: 20,
  },
  label: {
    fontSize: 18,
    fontWeight: '400',
    marginBottom: 5,
    textAlign: 'left',
    fontFamily: 'Pretendard',
  },
  input: {
    padding: 10,
    borderBottomWidth: 2,
    borderBottomColor: '#5772FF',
    fontSize: 18,
    color: '#5772FF',
    width: '100%',
    fontFamily: 'Pretendard',
  },
});
